name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Cấp quyền ghi để deploy

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Lấy toàn bộ lịch sử Git

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./build  # Sửa thành build nếu dùng React

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Tránh lỗi khi push lên gh-pages

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./build  # Sửa thành build nếu dùng React

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Sửa thành build nếu dùng React
          enable_jekyll: false  # Vô hiệu hóa Jekyll để tránh lỗi file `_config.yml`
